# Generated by Django 5.2.1 on 2025-07-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
