# Generated by Django 5.2.1 on 2025-05-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pebbler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pebbles', models.IntegerField(default=0)),
                ('trait', models.CharField(max_length=5)),
                ('quirk', models.CharField(max_length=12)),
                ('ability', models.TextField(max_length=14)),
                ('away_pebbles', models.IntegerField(default=0)),
                ('home_pebbles', models.IntegerField(default=0)),
                ('qp', models.IntegerField(default=0)),
                ('at', models.IntegerField(default=0)),
                ('masters', models.IntegerField(default=0)),
                ('all_stars', models.IntegerField(default=0)),
                ('professionals', models.IntegerField(default=0)),
                ('learners', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('division', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('away_roll', models.IntegerField(null=True)),
                ('home_roll', models.IntegerField(null=True)),
                ('away_quirk', models.BooleanField(default=False)),
                ('home_quirk', models.BooleanField(default=False)),
                ('away_ability', models.BooleanField(default=False)),
                ('home_ability', models.BooleanField(default=False)),
                ('away_roll_final', models.IntegerField(null=True)),
                ('home_roll_final', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
                ('home_score', models.IntegerField(null=True)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_bouts', to='league.pebbler')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_bouts', to='league.pebbler')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pebbles', models.IntegerField(default=0)),
                ('division', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('pf', models.IntegerField(default=0)),
                ('pa', models.IntegerField(default=0)),
                ('pd', models.IntegerField(default=0)),
                ('away_played', models.IntegerField(default=0)),
                ('home_played', models.IntegerField(default=0)),
                ('away_pebbles', models.IntegerField(default=0)),
                ('home_pebbles', models.IntegerField(default=0)),
                ('qp', models.IntegerField(default=0)),
                ('at', models.IntegerField(default=0)),
                ('form', models.CharField(default='', max_length=30)),
                ('rank', models.IntegerField()),
                ('previous_rank', models.IntegerField()),
                ('tiebreaker', models.FloatField()),
                ('pebbler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='league.pebbler')),
            ],
        ),
    ]
