# Generated by Django 5.2.1 on 2025-05-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_bout_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='away_roll_half',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bout',
            name='home_roll_half',
            field=models.IntegerField(null=True),
        ),
    ]
