# Generated by Django 5.2.1 on 2025-05-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_bout_away_roll_half_bout_home_roll_half'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='tiebreaker',
            field=models.IntegerField(),
        ),
    ]
