# Generated by Django 5.2.1 on 2025-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_performance_tiebreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pebbler',
            name='current_division',
            field=models.CharField(default='Master', max_length=12),
            preserve_default=False,
        ),
    ]
