# Generated by Django 5.2.1 on 2025-05-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_pebbler_current_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bout',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
