# Generated by Django 5.2.1 on 2025-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_bout_away_score_alter_bout_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='last_in_day',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
