# Generated by Django 5.2.1 on 2025-05-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_bout_last_in_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='pebbler',
            name='current_rank',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
