# Generated by Django 5.2.1 on 2025-05-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_pebbler_current_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pebbler',
            name='current_rank',
            field=models.IntegerField(null=True),
        ),
    ]
