# Generated by Django 5.2.1 on 2025-06-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_pebbler_current_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pebbler',
            name='description',
            field=models.CharField(default='Member of the Dynamic Dinos. Well-acclimated to windy environments with lots of leaves.', max_length=128),
            preserve_default=False,
        ),
    ]
