# Generated by Django 5.2.1 on 2025-07-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_pebbler_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pebbler',
            name='ytd_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pebbler',
            name='ytd_away_pebbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pebbler',
            name='ytd_home_pebbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pebbler',
            name='ytd_pebbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pebbler',
            name='ytd_qp',
            field=models.IntegerField(default=0),
        ),
    ]
