# Generated by Django 5.2.1 on 2025-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_pebbler_ytd_at_pebbler_ytd_away_pebbles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pebbler',
            name='isMale',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
