# Generated by Django 5.2.1 on 2025-11-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_pebbler_ismale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='division',
            field=models.CharField(max_length=12),
        ),
    ]
