# Generated by Django 5.2.1 on 2025-11-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_today'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Today',
        ),
    ]
