# Generated by Django 5.2.1 on 2026-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_delete_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolBoutID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
